// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"go-zero-study/rpc/internal/logic/user"
	"go-zero-study/rpc/internal/svc"
	"go-zero-study/rpc/types/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) UserInfo(ctx context.Context, in *user.UserInfoRequest) (*user.UserResponse, error) {
	l := userlogic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}

func (s *UserServer) Login(ctx context.Context, in *user.UserRequest) (*user.UserResponse, error) {
	l := userlogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) UserCreate(ctx context.Context, in *user.UserRequest) (*user.UserResponse, error) {
	l := userlogic.NewUserCreateLogic(ctx, s.svcCtx)
	return l.UserCreate(in)
}
